# Generated by Django 4.0.6 on 2022-07-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounttoken'),
        ('accounts', '0003_alter_customuseraccount_is_active'),
    ]

    operations = [
    ]
